on:
  push:
    branches:
      - master
    paths:
      - clusters/cluster-1/*
name: Update
jobs:
  build:
    name: Pulumi Deploy (Current Stack)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pulumi Deploy (Current Stack)
      uses: docker://pulumi/actions
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: up
        PULUMI_ROOT: clusters/cluster-1/
      with:
        args: up
