on:
  pull_request:
    paths:
      - eks-clusters/cluster-2/*
name: Preview
jobs:
  build:
    name: Pulumi Preview (Merged Stack)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pulumi Preview (Merged Stack)
        uses: docker://pulumi/actions
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          PULUMI_ROOT: eks-clusters/cluster-2/
        with:
          args: preview
